services:
  prefect:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./prefect
        - PREFECT_API_KEY=${PREFECT_API_KEY}
        - PREFECT_WORKSPACE=${PREFECT_WORKSPACE}
    environment:
      - LOG_LEVEL=info
      - BACKOFF_DAYS=1
    env_file:
      - .env
    command: ["python3", "main.py"]
    volumes:
      - ./prefect:/usr/src/app

  ohlcv:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    environment:
      - LOG_LEVEL=info
      - BACKOFF_DAYS=1
    env_file:
      - .env
    command: ["python3", "ohlcv.py"]
    volumes:
      - ./services:/usr/src/app
    depends_on:
      - redis

  vpin-1e3:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    environment:
      - LOG_LEVEL=info
      - INSTRUMENT_ID=1
      - VPIN_ID=1
      - BUCKET_SIZE=1000
      - OUTPUT=vpin_ohlcv
    env_file:
      - .env
    command: ["python3", "vpin.py"]
    volumes:
      - ./services:/usr/src/app

  vpin-2e2:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    environment:
      - LOG_LEVEL=info
      - INSTRUMENT_ID=1
      - VPIN_ID=2
      - BUCKET_SIZE=200
      - OUTPUT=vpin_ohlcv
    env_file:
      - .env
    command: ["python3", "vpin.py"]
    volumes:
      - ./services:/usr/src/app

  features-202406-1e3:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    environment:
      - LOG_LEVEL=info
      - INSTRUMENT_ID=1
      - VPIN_ID=1
      - SOURCE=vpin_ohlcv
      - OUTPUT=features_202406
      - LAG=32
    env_file:
      - .env
    command: ["python3", "features-202406.py"]
    volumes:
      - ./services:/usr/src/app

  features-202406-2e2:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    environment:
      - LOG_LEVEL=info
      - INSTRUMENT_ID=1
      - VPIN_ID=2
      - SOURCE=vpin_ohlcv
      - OUTPUT=features_202406
      - LAG=128
    env_file:
      - .env
    command: ["python3", "features-202406.py"]
    volumes:
      - ./services:/usr/src/app

  redis:
    image: redis:latest
    ports:
      - "9876:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    restart: on-failure

  monitor:
    build:
      context: ./monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
