services:
  prefect:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - PREFECT_API_KEY=${PREFECT_API_KEY}
        - PREFECT_WORKSPACE=${PREFECT_WORKSPACE}
    environment:
      - LOG_LEVEL=info
      # - PREFECT_LOGGING_LEVEL=DEBUG
    env_file:
      - .env
    working_dir: /usr/src/app/etl
    command: ["python3", "main.py"]

  redis:
    image: redis:latest
    ports:
      - "9876:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    restart: on-failure

  monitor:
    build:
      context: ./monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
