services:
  ohlcv:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    ports:
      - "8765:8000"
    environment:
      - LOG_LEVEL=info
      - BACKOFF_DAYS=1
    env_file:
      - .env
    command: ["python3", "ohlcv.py"]
    volumes:
      - ./services:/usr/src/app
    depends_on:
      - redis

  vpin-1e3:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    ports:
      - "8766:8000"
    environment:
      - LOG_LEVEL=info
    env_file:
      - .env
    command: ["python3", "vpin-1e3.py"]
    volumes:
      - ./services:/usr/src/app

  features-202406:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - BASE_DIR=./services
    ports:
      - "8767:8000"
    environment:
      - LOG_LEVEL=info
    env_file:
      - .env
    command: ["python3", "features-202406.py"]
    volumes:
      - ./services:/usr/src/app

  redis:
    image: redis:latest
    ports:
      - "9876:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    restart: on-failure

  monitor:
    build:
      context: ./monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
