-- +goose Up
CREATE TABLE IF NOT EXISTS features_202406 (
    id BIGSERIAL PRIMARY KEY,
    Instrument bigint NOT NULL,
    VPIN bigint NOT NULL,
    Epoch TIMESTAMP NOT NULL,
    Volume NUMERIC NOT NULL,
    Number bigint NOT NULL,
    imf_imf_0 NUMERIC,
    imf_imf_1 NUMERIC,
    imf_imf_2 NUMERIC,
    imf_imf_3 NUMERIC,
    imf_imf_4 NUMERIC,
    imf_imf_5 NUMERIC,
    imf_imf_6 NUMERIC,
    imf_imf_7 NUMERIC,
    imf_imf_8 NUMERIC,
    imf_ia_0 NUMERIC,
    imf_ia_1 NUMERIC,
    imf_ia_2 NUMERIC,
    imf_ia_3 NUMERIC,
    imf_ia_4 NUMERIC,
    imf_ia_5 NUMERIC,
    imf_ia_6 NUMERIC,
    imf_ia_7 NUMERIC,
    imf_ia_8 NUMERIC,
    imf_ip_0 NUMERIC,
    imf_ip_1 NUMERIC,
    imf_ip_2 NUMERIC,
    imf_ip_3 NUMERIC,
    imf_ip_4 NUMERIC,
    imf_ip_5 NUMERIC,
    imf_ip_6 NUMERIC,
    imf_ip_7 NUMERIC,
    imf_ip_8 NUMERIC,
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    Ask NUMERIC,
    Bid NUMERIC,
    Last NUMERIC,
    FOREIGN KEY (Instrument) REFERENCES instrument(id),
    FOREIGN KEY (VPIN) REFERENCES vpin(id)
);

-- +goose Down
DROP TABLE IF EXISTS features_202406;
